spring:
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      base-url: http://new-api.new-api.orb.local
      api-key: sk-v3tuADE9Fuzb3tJS014819A800Bb439bB6D9BcDb85696b15
      chat:
        options:
          model: gpt-4o
          temperature: 0.3
    retry:
      max-attempts: 3
      onClientErrors: true
      backoff:
        max-interval: 10000

server:
  port: 57001


# liteflow
liteflow:
  rule-source: rules/flow.el.xml
  # 使用自己的协程线程池
  monitor:
    enable-log: true
  when-max-workers: 64
  main-executor-works: 128
  parallel-max-workers: 64
tiegangan:
  wechat:
    host: http://10.105.55.3:7777