spring:
  threads:
    virtual:
      enabled: true

server:
  port: 57001



logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG